import { ThemeFactory, ThemeProduct } from './types';

export class ModernThemeFactory extends ThemeFactory {
  public createTheme(): ThemeProduct {
    return {
      appBg: 'bg-slate-50 text-slate-900 selection:bg-blue-200',
      appTexture: '',
      sidebarBg: 'bg-white border-slate-200',
      headerBg: 'bg-white border-slate-200',
      panelBg: 'bg-white border-slate-200 shadow-sm',
      panelInner: 'bg-slate-50 border-slate-200',
      modalBg: 'bg-white border-slate-200 text-slate-900 shadow-xl',
      modalTexture: '',
      modalHeaderBg: 'bg-slate-50 border-slate-200',
      modalFooterBg: 'bg-slate-50 border-slate-200',
      wellBg: 'bg-slate-50',
      wellInnerBg: 'bg-slate-50',
      textPrimary: 'text-slate-900',
      textSecondary: 'text-slate-500',
      textAccent: 'text-blue-600',
      textMuted: 'text-slate-600',
      borderBase: 'border-slate-200',
      borderAccent: 'border-blue-300',
      activeBadge: 'bg-blue-600 text-white',
      inactiveBadge: 'bg-white text-slate-600 hover:bg-blue-50 border border-slate-100',
      successBadge: 'bg-green-50 border-green-200 text-green-700',
      dangerBadge: 'bg-red-50 text-red-600 border-red-200',
      accentLightBg: 'bg-blue-50',
      accentSolidBg: 'bg-blue-600',
      mutedBg: 'bg-slate-100',
      indicatorBg: 'bg-slate-100',
      successLightBg: 'bg-green-50',
      dangerLightBg: 'bg-red-50',
      successText: 'text-green-700',
      dangerText: 'text-red-700',
      sliderAccent: 'accent-blue-600',
      progressFill: 'bg-blue-600',
      buttonPrimary: 'bg-white hover:bg-slate-50 text-slate-800 border-slate-300 shadow-sm',
      buttonHighlight: 'bg-blue-600 hover:bg-blue-700 text-white shadow-blue-500/20',
      buttonDanger: 'bg-red-50 hover:bg-red-100 text-red-700 border-red-200',
      buttonDangerSolid: 'bg-red-600 text-white hover:bg-red-700',
      dangerBg: 'bg-red-50 border-red-200 text-red-900',
      controlButton: 'bg-slate-100 hover:bg-slate-200 text-slate-600',
      controlButtonActive: 'bg-blue-600 text-white border-blue-600',
      secondaryButtonHover: 'hover:bg-blue-50',
      inputBg: 'bg-white border-slate-300 text-slate-900 focus:border-blue-500 focus:ring-1 focus:ring-blue-500',
      keyShape: 'rounded-md',
      keyBase: 'border-slate-300 bg-white shadow-sm hover:border-slate-400 hover:bg-slate-50 text-slate-700',
      keyPressed: 'bg-blue-100 text-blue-700 border-blue-400 ring-2 ring-blue-500/30 shadow-[0_0_10px_rgba(59,130,246,0.3)]',
      keyCompactBase: 'bg-white border border-slate-300 text-slate-700 shadow-sm hover:bg-slate-50',
      keyCompactPressed: 'bg-blue-100 border-blue-400 text-blue-700 ring-2 ring-blue-500/30',
      lampShape: 'rounded-md',
      lampBase: 'bg-slate-100 border-slate-300 text-slate-400 shadow-sm',
      lampLit: 'bg-blue-500 border-blue-400 text-white shadow-[0_0_15px_rgba(59,130,246,0.6)] font-bold scale-105',
      lampDim: 'bg-blue-50 border-blue-200 text-blue-600 shadow-sm animate-bulb-flicker',
      lampLitGlow: 'bg-yellow-400 text-yellow-950 shadow-sm',
      signalPulse: 'bg-yellow-400 text-yellow-950 shadow-sm',
      signalGradient: '',
      activeKeyBg: 'bg-yellow-900',
      activeKeyText: 'text-yellow-100',
      keyboardPanelBg: 'bg-white border-slate-200 shadow-sm',
      lampboardPanelBg: 'bg-slate-50 border-slate-200 shadow-sm',
      compactPlateBg: 'bg-white border border-slate-200 shadow-sm',
      paperTapeBg: 'bg-white text-slate-900 border border-slate-300',
      paperTapeText: 'text-slate-800',
      paperTapeBorder: 'border-blue-500',
      paperTapeBorderActive: 'border-blue-500',
      selectBg: 'bg-white text-slate-800 border-slate-300',
      fontHeader: 'font-sans font-semibold tracking-tight',
      fontBody: 'font-sans',
      fontMono: 'font-mono text-[0.9em]',
      fontRotor: 'font-sans font-bold text-slate-800',
      statusHighlight: 'bg-white border-blue-400 shadow-[0_0_15px_rgba(59,130,246,0.2)]',
      buttonSuccess: 'bg-green-600 hover:bg-green-700 text-white border-green-500 shadow-sm',
      buttonMuted: 'border-slate-200 bg-slate-50 text-slate-600 hover:bg-slate-100 hover:text-slate-700 shadow-xs',
      chartBarPlaintext: 'bg-slate-300 group-hover:bg-slate-400',
      chartBarCiphertext: 'bg-blue-600 group-hover:bg-blue-500 shadow-[0_0_6px_rgba(59,130,246,0.25)] group-hover:shadow-[0_0_10px_rgba(59,130,246,0.5)]',
      chartBarBaseline: 'border-slate-300',
      paperTapeCopyButton: 'bg-blue-600 text-white hover:bg-blue-700',
      rotorWindowBg: 'bg-white',
      rotorWindowBorder: 'border-slate-300',
      rotorWindowShadow: 'shadow-inner',
      rotorWindowControl: 'text-slate-400 hover:text-blue-500',
      lampLitDkl: 'bg-blue-600 border-blue-400 scale-105 shadow-[0_0_12px_rgba(59,130,246,0.5)]',
      lampLitSammler: 'bg-blue-600 border-blue-400 scale-105 shadow-[0_0_12px_rgba(59,130,246,0.5)]',
      lampDimDkl: 'bg-blue-50 border-blue-200 shadow-sm animate-bulb-flicker',
      lampDimSammler: 'bg-blue-50 border-blue-200 shadow-sm animate-bulb-flicker',
      lampInnerLitDkl: 'bg-blue-500 text-white font-bold',
      lampInnerLitSammler: 'bg-blue-500 text-white font-bold',
      lampInnerLitHell: 'bg-blue-500 text-white font-bold',
      lampSocketBg: 'bg-slate-200',
      lampSocketBorder: 'border-slate-300',
      lampSocketInnerBg: 'bg-slate-100',
      lampSocketInnerText: 'text-slate-400',
      lampSocketInnerShadow: '',
      litLampBadgeDkl: 'text-yellow-700 bg-yellow-100 border-yellow-300',
      litLampBadgeSammler: 'text-yellow-700 bg-yellow-100 border-yellow-300',
      litLampBadgeHell: 'text-yellow-700 bg-yellow-100 border-yellow-300',
      textureMetal: '',
      batteryPanelStop0: '#f8fafc',
      batteryPanelStop100: '#e2e8f0',
      batteryBrassStop0: '#3b82f6',
      batteryBrassStop40: '#2563eb',
      batteryBrassStop80: '#1d4ed8',
      batteryBrassStop100: '#1e40af',
      batteryBakeliteStop0: '#475569',
      batteryBakeliteStop40: '#334155',
      batteryBakeliteStop85: '#1e293b',
      batteryBakeliteStop100: '#0f172a',
      batteryPlateShadowOpacity: '0.15',
      batteryRectStroke: '#cbd5e1',
      batteryAxleFill: '#cbd5e1',
      batteryAxleStroke: '#94a3b8',
      batteryArcStroke: '#e2e8f0',
      batteryKnobBaseFill: '#1e293b',
      batteryKnobBaseStroke: '#475569',
      batteryKnobHandleStroke: '#0f172a',
      batteryKnobRidgeFill: '#334155',
      batteryKnobRidgeStroke: '#475569',
      batteryHubStroke: '#475569',
      batteryHubCenterFill: '#0f172a',
      batteryArrowStroke: '#1e40af',
      mixBlendMode: '',
      rotorDecoration: 'bg-blue-500/5',
      rotorDecorationHover: 'group-hover:bg-blue-500/10',
      applyButton: 'bg-blue-600 text-white hover:bg-blue-700 shadow-md active:translate-y-0.5',
      buttonDangerHighlight: 'bg-red-600 hover:bg-red-700 text-white',
      textDanger: 'text-red-600',
      borderDanger: 'border-red-200',
      dangerPanelBg: 'bg-red-50',
      buttonMutedHover: 'hover:bg-slate-100',
      rotorIconWrapper: 'bg-slate-100 border-4 border-slate-200 shadow-inner',
      textMutedAlt: 'text-slate-500',
      bgSuccess: 'bg-green-50',
      borderSuccess: 'border-green-200',
      textSuccess: 'text-green-700',
      bgSuccessStrong: 'bg-green-200',
      textSuccessStrong: 'text-green-800',
      bgSuccessDark: 'bg-white/50',
      borderSuccessAlt: 'border-green-100',
      textSuccessAlt: 'text-slate-500',
      bgDangerAlt: 'bg-red-50',
      borderDangerAlt: 'border-red-200',
      textDangerAlt: 'text-red-700',
      textDangerStrong: 'text-red-500',
      textDangerHeader: 'text-red-800',
      buttonActive: 'border-blue-500 text-blue-600',
      buttonInactive: 'border-transparent text-slate-500 hover:text-slate-700',
      rotorSettingPanelDecoration: 'bg-blue-500/5 group-hover:bg-blue-500/10',
      rotorSettingSelect: 'bg-white border-slate-300 text-slate-800 font-sans text-sm shadow-sm',
      rotorWindowControlAlt: 'text-slate-400 hover:text-blue-500 bg-white border border-slate-300',
      rotorWindowControlMuted: 'text-slate-400 hover:text-blue-500 hover:bg-slate-100',
      rotorWindowControlAction: 'text-slate-400 hover:text-blue-500',
      textMutedStrong: 'text-slate-600',
      borderStrong: 'border-slate-200',
      tableHeaderMuted: 'text-slate-500',
      tableRowHover: 'hover:bg-slate-50',
      tableRowActive: 'bg-blue-50',
      tableCellAccent: 'bg-slate-50 border-slate-200',
      textDangerStrongAlt: 'text-red-600',
      buttonSuccessSolid: 'bg-green-600 text-white hover:bg-green-700',
      buttonMutedSolid: 'bg-white hover:bg-slate-50 text-slate-800 border-slate-300 shadow-sm',
      tabActive: 'bg-blue-500 text-white',
      tabInactive: 'text-slate-500 hover:text-slate-700',
      inputBgAlt: 'bg-slate-50 border-slate-200',
      cardInteractive: 'bg-slate-50 hover:bg-slate-100 border-slate-200',
      bgSuccessFaint: 'bg-white/50 border-green-100',
      textSuccessFaint: 'text-slate-500',
      buttonDisabled: 'bg-slate-200 text-slate-400',
      rotorWindowContainer: 'bg-slate-100 border-slate-300 border shadow-inner',
      tableDayTag: 'bg-slate-50 border-slate-200',
      tabSwitchButton: 'bg-slate-100 border-slate-300 text-slate-600 hover:bg-slate-200',
      codebookHeaderButton: 'bg-blue-50 hover:bg-blue-100 text-blue-600 border-blue-200',
      indicatorBgAlt: 'bg-slate-50 text-slate-500 border-slate-200 shadow-sm',
      codebookSheetBg: 'bg-white text-slate-900 border-slate-200',
      codebookStamp: 'border-blue-600 text-blue-600',
      tableHeaderBg: 'bg-slate-50',
      kenngruppenTag: 'bg-blue-50 text-blue-700 border-blue-200 shadow-xs',
      textAccentExtra: 'text-blue-600',
      textAccentStrong: 'text-blue-700',
      bgAccentFaint: 'bg-blue-600/10',
      bgAccentSolid: 'bg-blue-600',
      bgAccentHover: 'bg-blue-700',
      circleIndicator: 'bg-blue-50 border-blue-200 text-blue-600',
      headerPreviewBadge: 'bg-slate-100 text-slate-900 border-slate-300 dark:bg-slate-800 dark:text-slate-100 dark:border-slate-700',
    };
  }
}
